# TechPulse Daily Configuration Template
# Copy this file to config.yaml and update with your settings

# OpenAI API Configuration
openai:
  api_key: "your-openai-api-key-here"
  model: "gpt-3.5-turbo"
  max_tokens: 500

# Database Configuration
database:
  url: "data/news.db"

# RSS Feed Sources
sources:
  - name: "TechCrunch"
    url: "https://techcrunch.com/feed/"
    category: "general"
  - name: "Ars Technica"
    url: "https://feeds.arstechnica.com/arstechnica/index"
    category: "general"
  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"
    category: "general"
  - name: "Wired"
    url: "https://www.wired.com/feed/rss"
    category: "general"

# Scraper Configuration
scraper:
  schedule_time: "08:00"
  max_articles_per_source: 50
  user_agent: "TechPulse Daily Bot 1.0"

# Output Configuration
output:
  generate_html: true
  generate_markdown: true
  output_dir: "daily_news"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/scraper.log"