general:
  run_time: "08:00"
  output_dir: "./daily_news"
  keep_days: 30
  max_articles_per_source: 20

sources:
  # General Tech
  - name: "TechCrunch"
    url: "https://techcrunch.com/feed/"
    type: "rss"
    categories: ["general", "startups"]
    
  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"
    type: "rss"
    categories: ["general"]
    
  - name: "Ars Technica"
    url: "https://feeds.arstechnica.com/arstechnica/index"
    type: "rss"
    categories: ["general"]
    
  - name: "Wired"
    url: "https://www.wired.com/feed/rss"
    type: "rss"
    categories: ["general"]
    
  # Startup & Venture Capital
  - name: "TechCrunch Startups"
    url: "https://techcrunch.com/category/startups/feed/"
    type: "rss"
    categories: ["emerging-tech", "general"]
    
  - name: "VentureBeat Startups"
    url: "https://venturebeat.com/category/entrepreneur/feed/"
    type: "rss"
    categories: ["emerging-tech", "ai"]
    
  # Financial News
  - name: "Financial Times Tech"
    url: "https://www.ft.com/technology?format=rss"
    type: "rss"
    categories: ["stock-market", "general"]
    
  - name: "Bloomberg Technology"
    url: "https://feeds.bloomberg.com/technology/news.rss"
    type: "rss"
    categories: ["stock-market", "general", "ai"]

summarization:
  api: "openai"
  model: "gpt-3.5-turbo"
  max_length: 100
  api_key: ""  # Set your OpenAI API key here

output:
  formats: ["html", "markdown"]
  include_summaries: true
  group_by_category: true
  
database:
  path: "./news_data.db"

logging:
  level: "INFO"
  file: "./logs/scraper.log"