services:
  techpulse-web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./daily_news:/app/daily_news
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  techpulse-scraper:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./daily_news:/app/daily_news
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONPATH=/app
    command: ["python", "tech_scraper.py", "--schedule"]
    restart: unless-stopped
    depends_on:
      - techpulse-web

volumes:
  data:
  logs:
  daily_news: